import type { DataSource } from '@/lib/types';

/**
 * Data source registry — the single place where source metadata lives.
 *
 * `verified` becomes true only after a real response has been fetched from the
 * endpoint and saved under /data/samples/<id>/. Licence strings marked
 * 'unknown — verify' have not been confirmed from the publisher yet.
 *
 * See DATA_SOURCES.md for the verification log.
 */
const UNVERIFIED_NETWORK =
  'ยังไม่ได้ตรวจสอบ: สภาพแวดล้อมที่ใช้พัฒนาระยะที่ 1 ถูกนโยบายเครือข่ายปิดกั้นโฮสต์นี้ — Not yet verified: host blocked by the build environment network policy (2026-09-29).';

const NOT_STARTED = 'ยังไม่ได้เริ่มตรวจสอบ (ระยะถัดไป) — Not yet investigated; scheduled for a later phase.';

export const SOURCES: readonly DataSource[] = [
  // ---------------------------------------------------------------- Phase 1
  {
    id: 'hdx.cod-ab-tha',
    organization: 'กรมแผนที่ทหาร ผ่าน UN OCHA (HDX)',
    organizationEn: 'Royal Thai Survey Department via UN OCHA (HDX)',
    datasetName: 'ขอบเขตการปกครองประเทศไทย ระดับจังหวัด อำเภอ ตำบล (COD-AB)',
    datasetNameEn: 'Thailand – Subnational Administrative Boundaries (COD-AB), ADM1–ADM3',
    kind: 'reference',
    license: 'Creative Commons Attribution for Intergovernmental Organisations (CC BY-IGO) — as stated on HDX',
    attribution: 'เขตการปกครอง: กรมแผนที่ทหาร / OCHA COD-AB (HDX)',
    endpoint: 'https://data.humdata.org/dataset/cod-ab-tha',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand ADM0–ADM3 (RTSD, valid_on 2022-01-22); stored here: Nakhon Si Thammarat (TH80) only',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: false,
    phase: 1,
    verificationNote: 'ตรวจสอบแล้ว: ดาวน์โหลด tha_admin_boundaries.shp.zip (HDX 2026-01-26) นำเข้า TH80 ได้ 1 จังหวัด 23 อำเภอ 170 ตำบล วันที่ข้อมูลจากฟิลด์ valid_on — Verified: imported TH80 = 1 province, 23 districts, 170 subdistricts; data date from valid_on.',
  },
  {
    id: 'dopa.villages',
    organization: 'กรมการปกครอง กระทรวงมหาดไทย',
    organizationEn: 'Department of Provincial Administration (DOPA), Ministry of Interior',
    datasetName: 'ข้อมูลที่ตั้งและสภาพทั่วไปของหมู่บ้าน (จังหวัดนครศรีธรรมราช)',
    datasetNameEn: 'Village locations and general conditions (Nakhon Si Thammarat)',
    kind: 'reference',
    license: 'Open Data Common — as stated on GD Catalog (verify exact terms)',
    attribution: 'ที่ตั้งหมู่บ้าน: กรมการปกครอง (GD Catalog)',
    endpoint: 'https://gdcatalog.go.th/dataset/gdpublish-gis-01',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Village points, one file per province; no หมู่ที่ field in the 2023 release; updated yearly',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: false,
    phase: 1,
    verificationNote: 'ตรวจสอบแล้ว: ไฟล์จริง (เผยแพร่ 5 ก.ย. 2566) ได้รับจากเจ้าของโครงการซึ่งดาวน์โหลดจาก URL ทางการ เพราะโฮสต์ opendata_tst.dopa.go.th เข้าถึงไม่ได้จากระบบ 1,636 ระเบียน นำเข้า 1,588 ปฏิเสธ 48 (พิกัดเป็นเมตร 7 จุด นอกจังหวัด 41 จุด ส่วนใหญ่ใช้พิกัดกรุงเทพฯ เป็นค่าแทน) — Verified with the real file (released 2023-09-05) supplied by the project owner from the official URL: 1,636 records, 1,588 imported, 48 rejected (7 projected coordinates, 41 outside the province, mostly a Bangkok placeholder point).',
  },
  {
    id: 'osm.geofabrik',
    organization: 'ผู้ร่วมพัฒนา OpenStreetMap (ไฟล์จาก Geofabrik)',
    organizationEn: 'OpenStreetMap contributors (extract by Geofabrik)',
    datasetName: 'แม่น้ำ ลำธาร คลอง แหล่งน้ำ ถนน ชายฝั่ง และสถานที่ จาก OpenStreetMap',
    datasetNameEn: 'OpenStreetMap rivers, streams, canals, water bodies, roads, coastline and places',
    kind: 'reference',
    license: 'ODbL 1.0 — https://opendatacommons.org/licenses/odbl/1-0/',
    attribution: '© ผู้ร่วมพัฒนา OpenStreetMap (ODbL)',
    endpoint: 'https://download.geofabrik.de/asia/thailand-latest.osm.pbf',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand extract, clipped to the province + 5 km; small-canal completeness varies by area',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 1,
    verificationNote: 'ยังไม่ได้ตรวจสอบ: download.geofabrik.de ตัดการเชื่อมต่อจากสภาพแวดล้อมพัฒนา (connection reset) — Not verified: Geofabrik resets connections from the build environment.',
  },
  {
    id: 'basemap.openfreemap',
    organization: 'OpenFreeMap',
    organizationEn: 'OpenFreeMap',
    datasetName: 'แผนที่ฐานแบบเวกเตอร์ (สว่าง / มืด)',
    datasetNameEn: 'Vector basemap tiles (Positron / Dark)',
    kind: 'reference',
    license: 'unknown — verify at https://openfreemap.org (map data ODbL © OpenStreetMap contributors)',
    attribution: 'OpenFreeMap © OpenMapTiles · ข้อมูล © ผู้ร่วมพัฒนา OpenStreetMap',
    endpoint: 'https://tiles.openfreemap.org/styles/positron',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Global',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: true,
    phase: 1,
    verificationNote: 'ตรวจสอบแล้ว: โหลด style positron ได้ (ยังต้องยืนยันเงื่อนไขการใช้งาน) — Verified: style JSON loads; usage terms still to confirm.',
  },
  {
    id: 'basemap.esri-imagery',
    organization: 'Esri (World Imagery: Vantor/Maxar, Earthstar Geographics และอื่น ๆ)',
    organizationEn: 'Esri (World Imagery: Vantor/Maxar, Earthstar Geographics and others)',
    datasetName: 'ภาพดาวเทียมความละเอียดสูง Esri World Imagery',
    datasetNameEn: 'Esri World Imagery (high-resolution satellite and aerial imagery)',
    kind: 'satellite_derived',
    license: 'Esri terms of use: free use with attribution; heavy or commercial use needs an ArcGIS account (verify before high-traffic use)',
    attribution: 'ภาพดาวเทียม © Esri World Imagery (Esri, Vantor, Earthstar Geographics, GIS User Community)',
    endpoint: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Global mosaic. Over the province: z18 (~0.6 m) everywhere sampled, z19 (~0.3 m) in the city and Pak Phanang (tilemap check 2026-10-02); deeper levels are enlarged. Capture dates vary by place and are not current conditions',
    verified: false,
    verifiedAt: null,
    optional: true,
    phase: 1,
    verificationNote: UNVERIFIED_NETWORK,
  },
  {
    id: 'basemap.opentopomap',
    organization: 'OpenTopoMap',
    organizationEn: 'OpenTopoMap',
    datasetName: 'แผนที่ภูมิประเทศ',
    datasetNameEn: 'Topographic raster tiles',
    kind: 'reference',
    license: 'unknown — verify (OpenTopoMap states CC-BY-SA)',
    attribution: 'ข้อมูล © ผู้ร่วมพัฒนา OpenStreetMap, SRTM · รูปแบบ © OpenTopoMap (CC-BY-SA)',
    endpoint: 'https://tile.opentopomap.org/{z}/{x}/{y}.png',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Global; fair-use tile policy',
    verified: false,
    verifiedAt: null,
    optional: true,
    phase: 1,
    verificationNote: UNVERIFIED_NETWORK,
  },

  {
    id: 'basemap.terrain-aws',
    organization: 'Mapzen / AWS Open Data (Terrain Tiles)',
    organizationEn: 'Mapzen / AWS Open Data (Terrain Tiles)',
    datasetName: 'ความสูงภูมิประเทศสำหรับมุมมอง 3 มิติ',
    datasetNameEn: 'Elevation for the 3D view',
    kind: 'reference',
    license: 'Open data; attribution per https://github.com/tilezen/joerd/blob/master/docs/attribution.md (includes SRTM, GMTED2010, ETOPO1)',
    attribution: 'ภูมิประเทศ: Mapzen Terrain Tiles (AWS Open Data; SRTM, GMTED2010, ETOPO1)',
    endpoint: 'https://registry.opendata.aws/terrain-tiles/',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Global; ~30 m in Thailand (SRTM)',
    verified: true,
    verifiedAt: '2026-10-01',
    optional: true,
    phase: 1,
    verificationNote: 'ตรวจสอบแล้ว: ดึงไทล์ terrarium ได้ (HTTP 200) ใช้เฉพาะมุมมอง 3 มิติ — Verified: terrarium tiles load; used only in the 3D view.',
  },

  // ---------------------------------------------------------------- Phase 2
  {
    id: 'thaiwater.waterlevel',
    organization: 'สถาบันสารสนเทศทรัพยากรน้ำ (สสน.)',
    organizationEn: 'Hydro-Informatics Institute (HII)',
    datasetName: 'ระดับน้ำ (ThaiWater)',
    datasetNameEn: 'Water level (ThaiWater)',
    kind: 'station_observation',
    license: 'unknown — verify',
    attribution: 'ระดับน้ำ: สถาบันสารสนเทศทรัพยากรน้ำ (สสน.) — ThaiWater',
    endpoint: 'https://api-v3.thaiwater.net/api/v1/thaiwater30/public/waterlevel_load',
    requiresKey: false,
    expectedUpdateMinutes: 60,
    coverage: 'Thailand, ~800 telemetry stations from HII, RID, DDPM and others; 28 within the province + 5 km',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/thaiwater.waterlevel/waterlevel_load.json เวลาในข้อมูลไม่มีเขตเวลา ถือเป็นเวลาไทย (+07:00) จากหลักฐานในข้อมูล (ต้องยืนยันกับ สสน.) — Verified with a real sample; timestamps have no timezone and are read as Thai time (+07:00), inferred from the data (confirm with HII).',
  },
  {
    id: 'thaiwater.rain24h',
    organization: 'สถาบันสารสนเทศทรัพยากรน้ำ (สสน.)',
    organizationEn: 'Hydro-Informatics Institute (HII)',
    datasetName: 'ปริมาณฝนสะสม 24 ชั่วโมง (ThaiWater)',
    datasetNameEn: '24-hour rainfall (ThaiWater)',
    kind: 'station_observation',
    license: 'unknown — verify',
    attribution: 'ฝน 24 ชม.: สถาบันสารสนเทศทรัพยากรน้ำ (สสน.) — ThaiWater',
    endpoint: 'https://api-v3.thaiwater.net/api/v1/thaiwater30/public/rain_24h',
    requiresKey: false,
    expectedUpdateMinutes: 60,
    coverage: 'Thailand, ~4,400 rain stations from DWR, RID, HII, DDPM and others; 163 within the province + 5 km',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/thaiwater.rain24h/rain_24h.json เวลาในข้อมูลไม่มีเขตเวลา ถือเป็นเวลาไทย (+07:00) จากหลักฐานในข้อมูล (ต้องยืนยันกับ สสน.) — Verified with a real sample; timestamps have no timezone and are read as Thai time (+07:00), inferred from the data (confirm with HII).',
  },
  {
    id: 'tmd.weather',
    organization: 'กรมอุตุนิยมวิทยา',
    organizationEn: 'Thai Meteorological Department (TMD)',
    datasetName: 'ผลการตรวจอากาศ',
    datasetNameEn: 'Weather observations',
    kind: 'station_observation',
    license: 'TMD copyright; non-commercial redistribution must credit กรมอุตุนิยมวิทยา each time it is shown — verify terms',
    attribution: 'ข้อมูลอุตุนิยมวิทยา: กรมอุตุนิยมวิทยา',
    endpoint: 'https://data.tmd.go.th/api/Weather3Hours/V2/',
    requiresKey: false,
    expectedUpdateMinutes: 180,
    coverage: 'Thailand, 116 synoptic and agromet stations; 3 inside the province + 5 km (นครศรีธรรมราช, นครศรีธรรมราช สกษ., ฉวาง)',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/tmd.weather/ (Weather3Hours V2) ทุก 3 ชั่วโมง เวลาเป็นเวลาไทย (MM/DD/YYYY) หน่วยตามที่กรมอุตุฯ ระบุ (°C, %, กม./ชม., มม.) ใช้บัญชีสาธิตที่กรมอุตุฯ เผยแพร่ (uid=api) จนกว่าจะตั้ง TMD_UID/TMD_UKEY — Verified with the real sample; Thai local time; units as TMD states them; uses TMD\'s published demo account until TMD_UID/TMD_UKEY are set.',
  },
  {
    id: 'tmd.warnings',
    organization: 'กรมอุตุนิยมวิทยา',
    organizationEn: 'Thai Meteorological Department (TMD)',
    datasetName: 'ข่าวเตือนภัยสภาพอากาศ',
    datasetNameEn: 'Weather warnings',
    kind: 'warning',
    license: 'TMD copyright; credit กรมอุตุนิยมวิทยา — verify terms',
    attribution: 'คำเตือน: กรมอุตุนิยมวิทยา',
    endpoint: 'https://data.tmd.go.th/api/WeatherWarningNews/v2/',
    requiresKey: false,
    expectedUpdateMinutes: 180,
    coverage: 'Thailand (national announcements; the text names the regions affected)',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/tmd.warnings/ ประกาศระดับประเทศพร้อมช่วงเวลามีผลและลิงก์ประกาศฉบับเต็ม — Verified with the real sample: national announcements with effective period and link to the full text.',
  },
  {
    id: 'tmd.earthquake',
    organization: 'กรมอุตุนิยมวิทยา',
    organizationEn: 'Thai Meteorological Department (TMD)',
    datasetName: 'แผ่นดินไหวรายวัน (DailySeismicEvent)',
    datasetNameEn: 'Daily seismic events',
    kind: 'station_observation',
    license: 'TMD copyright; credit กรมอุตุนิยมวิทยา — verify terms',
    attribution: 'แผ่นดินไหว: กรมอุตุนิยมวิทยา',
    endpoint: 'https://data.tmd.go.th/api/',
    requiresKey: true,
    expectedUpdateMinutes: 1440,
    coverage: 'Thailand and region',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 2,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'usgs.earthquakes',
    organization: 'สำนักงานสำรวจธรณีวิทยาสหรัฐฯ (USGS)',
    organizationEn: 'U.S. Geological Survey (USGS)',
    datasetName: 'แผ่นดินไหว M4 ขึ้นไปในรัศมี 2,000 กม. (USGS ComCat)',
    datasetNameEn: 'Earthquakes M4+ within 2,000 km (USGS ComCat)',
    kind: 'station_observation',
    license: 'U.S. public domain (USGS-authored data, per USGS "Copyrights and Credits" policy) — policy page not reachable from the build environment; verify',
    attribution: 'แผ่นดินไหว: USGS (ComCat)',
    endpoint: 'https://earthquake.usgs.gov/fdsnws/event/1/query',
    requiresKey: false,
    expectedUpdateMinutes: 15,
    coverage: 'Global catalog; queried here within 2,000 km of the province centre, M ≥ 4.0, last 30 days. Smaller local events are often not listed (TMD is the source for those)',
    verified: true,
    verifiedAt: '2026-10-01',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/usgs.earthquakes/query.geojson เวลาเป็นมิลลิวินาที UTC ขนาด สถานที่ และสถานะ (automatic / reviewed) เป็นของ USGS ไม่มีการคำนวณเพิ่ม — Verified with a real response; times are epoch ms UTC; magnitude, place and review status are USGS\'s own.',
  },
  {
    id: 'nst.cctv',
    organization: 'เทศบาลนครนครศรีธรรมราช (NST Smart City CCTV)',
    organizationEn: 'Nakhon Si Thammarat City Municipality (NST Smart City CCTV)',
    datasetName: 'กล้องวงจรปิดเมืองนครศรีธรรมราช: ตำแหน่ง สถานะ และภาพสด',
    datasetNameEn: 'Nakhon Si Thammarat city CCTV: locations, status and live view',
    kind: 'station_observation',
    license: 'เผยแพร่สาธารณะบนเว็บไซต์ของเทศบาล ยังไม่พบเงื่อนไขการใช้งานที่ระบุชัด (ควรขออนุญาตเทศบาล) — Published openly by the municipality; no explicit terms of use found (permission from the municipality recommended)',
    attribution: 'กล้อง CCTV: เทศบาลนครนครศรีธรรมราช (nstcctv.nakhoncity.org)',
    endpoint: 'https://nstcctv.nakhoncity.org/',
    requiresKey: false,
    expectedUpdateMinutes: 1,
    coverage: 'Cameras of the city municipality (Mueang district): traffic, school fronts, water level, safety zones. Locations and status from the municipality; video plays in the municipality\'s own player',
    verified: true,
    verifiedAt: '2026-10-02',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: /api/cameras/public ให้รหัส ชื่อ กลุ่ม และพิกัด 222 กล้อง /api/camera-status ให้สถานะ online/offline ภาพสดเปิดผ่านเครื่องเล่นของเทศบาล (/cam/<id>_sub/) ไม่ผ่านระบบนี้ — Verified: 222 cameras with id, name, group and coordinates; status from /api/camera-status; live video is the municipality\'s own player, not relayed by this app.',
  },
  {
    id: 'community.reports',
    organization: 'ประชาชนผู้ใช้ Nakhonsi360',
    organizationEn: 'Members of the public using Nakhonsi360',
    datasetName: 'รายงานภัยพิบัติจากประชาชน (ยังไม่ยืนยัน)',
    datasetNameEn: 'Hazard reports from the public (unverified)',
    kind: 'community',
    license: 'รายงานที่ผู้ใช้ส่งเข้ามา แสดงเฉพาะส่วนที่ไม่ใช่ข้อมูลติดต่อ — User-submitted; contact details are never published',
    attribution: 'รายงานจากประชาชน (ยังไม่ยืนยัน)',
    endpoint: 'https://github.com/nexzerf/nakhonsi360/blob/main/REPORTS.md',
    requiresKey: false,
    expectedUpdateMinutes: 1,
    coverage: 'Nakhon Si Thammarat + 5 km; reports from the last 72 hours on the map',
    verified: true,
    verifiedAt: '2026-10-01',
    optional: false,
    phase: 2,
    verificationNote: 'ข้อมูลจากผู้ใช้ ไม่ใช่ข้อมูลทางการ ไม่ได้ตรวจสอบจนกว่าผู้ปฏิบัติงานจะอัปเดตสถานะ — Reported by the public, not official; unverified until a responder updates its status.',
  },
  {
    id: 'air4thai.aqi',
    organization: 'กรมควบคุมมลพิษ',
    organizationEn: 'Pollution Control Department (PCD) — Air4Thai',
    datasetName: 'คุณภาพอากาศ PM2.5 / AQI',
    datasetNameEn: 'Air quality PM2.5 / AQI',
    kind: 'station_observation',
    license: 'unknown — verify',
    attribution: 'คุณภาพอากาศ: กรมควบคุมมลพิษ (Air4Thai)',
    endpoint: 'https://air4thai.pcd.go.th/services/getNewAQI_JSON.php',
    requiresKey: false,
    expectedUpdateMinutes: 60,
    coverage: 'Thailand, 173 PCD stations; 1 inside the province (89t, ต.คลัง อ.เมือง)',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/air4thai.aqi/ เซิร์ฟเวอร์ส่งใบรับรองไม่ครบ ระบบดึงใบรับรองตัวกลางจากลิงก์ AIA ในใบรับรองเองแล้วตรวจสอบเต็มรูปแบบ (ไม่ได้ปิดการตรวจสอบ) ระดับและสีตามที่ คพ. ประกาศ — Verified with the real sample. The server sends an incomplete chain; the missing issuers are fetched from the certificate\'s own AIA links and the connection is fully verified (never disabled). Levels and colours as PCD publishes them.',
  },
  {
    id: 'gistda.pm25',
    organization: 'สำนักงานพัฒนาเทคโนโลยีอวกาศและภูมิสารสนเทศ (GISTDA)',
    organizationEn: 'GISTDA',
    datasetName: 'PM2.5 รายอำเภอจากดาวเทียม (รายชั่วโมง)',
    datasetNameEn: 'Hourly PM2.5 per district from satellite data',
    kind: 'satellite_derived',
    license: 'Public GISTDA service (pm25.gistda.or.th) — verify terms',
    attribution: 'PM2.5 รายอำเภอ: GISTDA (ค่าประมาณจากดาวเทียม)',
    endpoint: 'https://pm25.gistda.or.th/rest/getPm25byAmphoe?pv_idn=80',
    requiresKey: false,
    expectedUpdateMinutes: 120,
    coverage: 'All 23 districts of the province, one estimate per district per hour',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/gistda.pm25/ เป็นค่าประมาณทั้งอำเภอจากดาวเทียมและแบบจำลอง ไม่ใช่สถานีวัด เวลาลงท้าย Z แต่เป็นเวลาไทย — Verified with the real sample: a district-wide estimate from satellite data and models, not a monitor; times end in Z but are Thai local time.',
  },
  {
    id: 'gistda.flood',
    organization: 'สำนักงานพัฒนาเทคโนโลยีอวกาศและภูมิสารสนเทศ (GISTDA)',
    organizationEn: 'Geo-Informatics and Space Technology Development Agency (GISTDA)',
    datasetName: 'พื้นที่น้ำท่วมจากดาวเทียม และพื้นที่น้ำท่วมซ้ำซาก',
    datasetNameEn: 'Satellite flood extent and recurrent flood areas',
    kind: 'satellite_derived',
    license: 'GISTDA API gateway terms (registered API key; attribution to GISTDA)',
    attribution: 'น้ำท่วมจากดาวเทียม: GISTDA',
    endpoint: 'https://api-gateway.gistda.or.th/api/2.0/resources/features/flood/7days',
    requiresKey: true,
    expectedUpdateMinutes: 1440,
    coverage: 'Thailand; H3 cells of flood water detected from satellite (Sentinel-1, Radarsat-2 and others) in rolling 1/3/7/30-day windows. Filtered to the province with pv_idn=80',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้วด้วยคีย์จริง: /features/flood/7days?pv_idn=80 ตอบ GeoJSON (ช่อง H3 พร้อมอำเภอ ตำบล พื้นที่ ประชากร อาคาร ภาพดาวเทียมที่ใช้) วันที่ 3 ต.ค. 2569 นครศรีธรรมราชไม่มีพื้นที่น้ำท่วม (0) ทั้งประเทศ 121,916 ช่องใน 30 วัน — Verified with a real key: GeoJSON H3 cells with district, subdistrict, area, population, buildings and satellite scenes; 0 cells for the province on 2026-10-03 (121,916 nationally over 30 days).',
  },
  {
    id: 'gistda.flood-recurrent',
    organization: 'สำนักงานพัฒนาเทคโนโลยีอวกาศและภูมิสารสนเทศ (GISTDA)',
    organizationEn: 'Geo-Informatics and Space Technology Development Agency (GISTDA)',
    datasetName: 'พื้นที่น้ำท่วมซ้ำซาก ปี 2554–2563 (ภาคใต้)',
    datasetNameEn: 'Recurrent flood areas 2011–2020 (southern Thailand)',
    kind: 'satellite_derived',
    license: 'GISTDA open map service (copyright: GISTDA) — verify terms',
    attribution: 'น้ำท่วมซ้ำซาก 2554–2563: GISTDA',
    endpoint: 'https://gistdaportal.gistda.or.th/data/rest/services/FL_Flood/flood_freq11_20/MapServer',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Southern Thailand, flood frequency per area 2011–2020 (1–9 years), GISTDA classes and colours',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: บริการแผนที่แบบแคชของ GISTDA (FL_Flood/flood_freq11_20) จำนวนปีที่น้ำท่วมใน 10 ปี (2554–2563) สีตามที่ GISTDA กำหนด แผนที่แสดงโดยตรงจาก GISTDA — Verified: GISTDA cached map service; number of flooded years out of ten, GISTDA\'s own colours; tiles load directly from GISTDA.',
  },
  {
    id: 'gistda.hotspots',
    organization: 'สำนักงานพัฒนาเทคโนโลยีอวกาศและภูมิสารสนเทศ (GISTDA)',
    organizationEn: 'GISTDA',
    datasetName: 'จุดความร้อนรายวัน',
    datasetNameEn: 'Daily fire hotspots',
    kind: 'satellite_derived',
    license: 'unknown — verify',
    attribution: 'จุดความร้อน: GISTDA',
    endpoint: 'https://fire.gistda.or.th',
    requiresKey: false,
    expectedUpdateMinutes: 1440,
    coverage: 'Thailand',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว (/features/viirs/{1day,3days,7days}) แต่ไม่ได้ใช้ เพราะเป็นข้อมูล VIIRS ชุดเดียวกับ NASA FIRMS จะทำให้จุดซ้ำ — Verified (/features/viirs/...) but not used: the same VIIRS detections as NASA FIRMS, which would draw every point twice.',
  },
  {
    id: 'firms.hotspots',
    organization: 'NASA FIRMS',
    organizationEn: 'NASA Fire Information for Resource Management System',
    datasetName: 'จุดความร้อน VIIRS / MODIS (สำรอง)',
    datasetNameEn: 'VIIRS / MODIS active fire (backup)',
    kind: 'satellite_derived',
    license: 'NASA open data (free with MAP_KEY; cite NASA FIRMS)',
    attribution: 'จุดความร้อน: NASA FIRMS (VIIRS/MODIS)',
    endpoint: 'https://firms.modaps.eosdis.nasa.gov/api/area/csv/[MAP_KEY]/[SOURCE]/[AREA]/[DAYS]',
    requiresKey: true,
    expectedUpdateMinutes: 180,
    coverage: 'Global',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: true,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้วด้วยคีย์จริง: CSV จาก VIIRS (SNPP, NOAA-20, NOAA-21) และ MODIS ในกรอบจังหวัด เวลา acq_date/acq_time เป็น UTC — Verified with a real key: CSV from VIIRS (SNPP, NOAA-20, NOAA-21) and MODIS for the province extent; acq_date/acq_time are UTC.',
  },

  // ---------------------------------------------------------------- Phase 3
  {
    id: 'gistda.soilmoisture',
    organization: 'NASA (SMAP) ผ่าน GIBS',
    organizationEn: 'NASA SMAP via NASA GIBS',
    datasetName: 'ความชื้นดินผิวหน้า SMAP L4 (วิเคราะห์รายวัน)',
    datasetNameEn: 'SMAP L4 analysed surface soil moisture (daily)',
    kind: 'satellite_derived',
    license: 'NASA open data (no restrictions; cite NASA GIBS / SMAP)',
    attribution: 'ความชื้นในดิน: NASA SMAP L4 (GIBS)',
    endpoint: 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/SMAP_L4_Analyzed_Surface_Soil_Moisture/',
    requiresKey: false,
    expectedUpdateMinutes: 2880,
    coverage: 'Global, 9 km grid, daily (about 2–3 days behind)',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 3,
    verificationNote: 'ตรวจสอบแล้ว: ชั้น GIBS ใน EPSG:3857 (ถึงระดับ 6) วันล่าสุดที่มีข้อมูลอ่านจาก GetCapabilities ทุกครั้งที่ปรับปรุง ความละเอียด 9 กม. จึงหยาบมากในระดับจังหวัด GISTDA ยังไม่มีบริการความชื้นดินที่เปิดสาธารณะ — Verified: GIBS layer to level 6; the latest date comes from GetCapabilities at each refresh. 9 km cells are coarse at province scale. No public GISTDA soil-moisture service was found.',
  },
  {
    id: 'dmr.landslide',
    organization: 'กรมทรัพยากรธรณี',
    organizationEn: 'Department of Mineral Resources (DMR)',
    datasetName: 'ธรณีพิบัติภัย: ความอ่อนไหวต่อดินถล่ม หมู่บ้านเสี่ยงภัย จุดปลอดภัยชั่วคราว พื้นที่น้ำป่าไหลหลาก',
    datasetNameEn: 'Geohazards: landslide susceptibility, villages at risk, temporary safe points, flash flood/debris flow areas',
    kind: 'survey',
    license: 'Creative Commons Attribution (as stated on GD Catalog)',
    attribution: 'ธรณีพิบัติภัย: กรมทรัพยากรธรณี (GD Catalog, CC BY)',
    endpoint: 'https://gisportal.dmr.go.th/arcgis/rest/services/HAZARD',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand; community-level surveys. Village and safe-point records carry the survey year (Buddhist era, as written by DMR). Susceptibility is an assessment, not a forecast',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 3,
    verificationNote: 'ตรวจสอบแล้ว: ดึงจาก ArcGIS REST ของกรมทรัพยากรธรณีด้วยกรอบจังหวัด แล้วตัดเฉพาะในจังหวัด +5 กม. ได้ความอ่อนไหวดินถล่ม 1,187 พื้นที่ หมู่บ้านเสี่ยง 590 จุดปลอดภัย 571 พื้นที่น้ำป่าไหลหลาก 334 (นับ ณ 3 ต.ค. 2569) — Verified: queried the DMR ArcGIS services for the province extent and clipped to the province + 5 km: 1,187 susceptibility zones, 590 villages at risk, 571 safe points, 334 flash-flood/debris-flow areas (counts on 2026-10-03).',
  },
  {
    id: 'dmr.shoreline',
    organization: 'กรมทรัพยากรธรณี',
    organizationEn: 'Department of Mineral Resources (DMR)',
    datasetName: 'การเปลี่ยนแปลงแนวชายฝั่งทะเล (เส้นและพื้นที่กัดเซาะ/สะสมตัว)',
    datasetNameEn: 'Shoreline change (lines and erosion/accretion areas)',
    kind: 'survey',
    license: 'Creative Commons Attribution (as stated on GD Catalog)',
    attribution: 'การเปลี่ยนแปลงชายฝั่ง: กรมทรัพยากรธรณี (GD Catalog, CC BY)',
    endpoint: 'https://gisportal.dmr.go.th/arcgis/rest/services/ENVI',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thai coasts; each record states its compilation year (2015–2019 for this province) — not current conditions',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 3,
    verificationNote: 'ตรวจสอบแล้ว: เส้นการเปลี่ยนแปลงชายฝั่ง 62 ช่วง และพื้นที่กัดเซาะ/สะสมตัว 57 พื้นที่ในจังหวัด ปีข้อมูล 2015–2019 — Verified: 62 shoreline-change segments and 57 erosion/accretion areas in the province; data years 2015–2019.',
  },
  {
    id: 'dmcr.coast',
    organization: 'กรมทรัพยากรทางทะเลและชายฝั่ง',
    organizationEn: 'Department of Marine and Coastal Resources (DMCR)',
    datasetName: 'แนวป่าชายเลนของ ทช.',
    datasetNameEn: 'DMCR mangrove forest zones',
    kind: 'survey',
    license: 'Published by DMCR, hosted on GISTDA\'s open portal — verify terms',
    attribution: 'ป่าชายเลน: กรมทรัพยากรทางทะเลและชายฝั่ง (ผ่าน GISTDA)',
    endpoint: 'https://gistdaportal.gistda.or.th/arcgis/rest/services/Hosted/14_แนวป่าชายเลนของทช/FeatureServer/0',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand coasts; 111 mangrove polygons in the province extent',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 3,
    verificationNote: 'ตรวจสอบแล้ว: เว็บแผนที่ของ ทช. (marinegiscenter.dmcr.go.th) หาชื่อโดเมนไม่พบ จึงใช้ชั้น "แนวป่าชายเลนของ ทช." ที่ GISTDA เผยแพร่ (ชื่อ พื้นที่ไร่ รหัส) ไม่ระบุปีข้อมูล — Verified: DMCR\'s own map host does not resolve; the DMCR mangrove layer published on GISTDA\'s portal is used (name, area, id; no data year stated).',
  },
  {
    id: 'ldd.landuse',
    organization: 'กรมพัฒนาที่ดิน',
    organizationEn: 'Land Development Department (LDD)',
    datasetName: 'แผนที่การใช้ที่ดิน (แคชแผนที่)',
    datasetNameEn: 'Land use map (cached tiles)',
    kind: 'survey',
    license: 'Public map service of the Land Development Department — verify terms',
    attribution: 'การใช้ที่ดิน: กรมพัฒนาที่ดิน',
    endpoint: 'https://eis.ldd.go.th/arcgis/rest/services/LDD_LU_WM_CACHE/MapServer',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand; Web Mercator tiles to level 19; data year not stated by the service',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 3,
    verificationNote: 'ตรวจสอบแล้ว: แผนที่การใช้ที่ดินแบบแคชของกรมพัฒนาที่ดิน (LDD_LU_WM_CACHE) แสดงภาพโดยตรงจาก พด. บริการไม่ระบุปีข้อมูลและคำอธิบายสี — Verified: LDD cached land-use map, tiles load directly from LDD; the service states no data year and no legend.',
  },
  {
    id: 'dwr.wetlands',
    organization: 'กรมทรัพยากรน้ำ',
    organizationEn: 'Department of Water Resources (DWR)',
    datasetName: 'ทะเบียนพื้นที่ชุ่มน้ำ (สผ. ปรับปรุง 1 ต.ค. 2563)',
    datasetNameEn: 'Wetland register (ONEP, revised 1 Oct 2020)',
    kind: 'survey',
    license: 'Public ArcGIS service of the Department of Water Resources — verify terms',
    attribution: 'พื้นที่ชุ่มน้ำ: สผ. / กรมทรัพยากรน้ำ',
    endpoint: 'https://gis.dwr.go.th/arcgis/rest/services/',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand; in the province extent 6 registered wetlands (e.g. อ่าวปากพนัง, ทะเลน้อย)',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: false,
    phase: 3,
    verificationNote: 'ตรวจสอบแล้ว: ArcGIS REST ของกรมทรัพยากรน้ำ (Ramsar_Wetland_Revise_1Oct2020_by_ONEP) ไม่ใช้ชั้น "พื้นที่ชุ่มน้ำท้องถิ่น" เพราะชื่อและประเภทในข้อมูลต้นทางเข้ารหัสอักษรไทยผิด (อ่านไม่ได้) ไฟล์ดาวน์โหลดบน webgis ต้องเข้าสู่ระบบ — Verified: DWR ArcGIS REST. The "local wetlands" layer is not used: its Thai names and types are garbled at the source. The webgis download files need a login.',
  },

  // ---------------------------------------------------------------- Phase 4
  {
    id: 'copernicus.sentinel2',
    organization: 'ESA Copernicus (Sentinel-2) ผ่าน Microsoft Planetary Computer',
    organizationEn: 'ESA Copernicus Sentinel-2 via Microsoft Planetary Computer',
    datasetName: 'ภาพ Sentinel-2 L2A ล่าสุดที่เมฆน้อย (10 ม.)',
    datasetNameEn: 'Latest low-cloud Sentinel-2 L2A imagery (10 m)',
    kind: 'satellite_derived',
    license: 'Copernicus Sentinel data terms (free, full and open; credit "Contains modified Copernicus Sentinel data")',
    attribution: 'Contains modified Copernicus Sentinel data',
    endpoint: 'https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a',
    requiresKey: false,
    expectedUpdateMinutes: 1440,
    coverage: 'Province: the least cloudy scene of the last 120 days for each of the 6 Sentinel-2 tiles over it',
    verified: true,
    verifiedAt: '2026-10-03',
    optional: true,
    phase: 4,
    verificationNote: 'ตรวจสอบแล้ว: ค้นภาพจาก STAC ของ Planetary Computer เลือกภาพเมฆน้อยที่สุดต่อช่องกริด Sentinel-2 แล้วสร้างโมเสก วันที่ของแต่ละภาพแสดงในข้อมูลชั้น ภาพมีเมฆบางส่วนได้ — Verified: least-cloudy scene per Sentinel-2 tile from the Planetary Computer STAC, mosaicked; each scene date is shown; some cloud may remain.',
  },
];

const byId = new Map(SOURCES.map((s) => [s.id, s]));

export function getSource(id: string): DataSource {
  const s = byId.get(id);
  if (!s) throw new Error(`Unknown data source: ${id}`);
  return s;
}

export function findSource(id: string): DataSource | undefined {
  return byId.get(id);
}

/** Static sources loaded into Postgres by the import scripts. */
export const IMPORTED_SOURCE_IDS = ['hdx.cod-ab-tha', 'dopa.villages', 'osm.geofabrik', 'dmr.landslide', 'dmr.shoreline', 'dwr.wetlands', 'dmcr.coast', 'copernicus.sentinel2', 'gistda.soilmoisture'] as const;

/** Map tiles the browser loads straight from the agency (or through our tile relay): no import, always "external". */
export const EXTERNAL_TILE_SOURCE_IDS: readonly string[] = ['gistda.flood-recurrent', 'ldd.landuse'];
export type ImportedSourceId = (typeof IMPORTED_SOURCE_IDS)[number];
