import type { DataSource } from '@/lib/types';

/**
 * Data source registry — the single place where source metadata lives.
 *
 * `verified` becomes true only after a real response has been fetched from the
 * endpoint and saved under /data/samples/<id>/. Licence strings marked
 * 'unknown — verify' have not been confirmed from the publisher yet.
 *
 * See DATA_SOURCES.md for the verification log.
 */
const UNVERIFIED_NETWORK =
  'ยังไม่ได้ตรวจสอบ: สภาพแวดล้อมที่ใช้พัฒนาระยะที่ 1 ถูกนโยบายเครือข่ายปิดกั้นโฮสต์นี้ — Not yet verified: host blocked by the build environment network policy (2026-09-29).';

const NOT_STARTED = 'ยังไม่ได้เริ่มตรวจสอบ (ระยะถัดไป) — Not yet investigated; scheduled for a later phase.';

export const SOURCES: readonly DataSource[] = [
  // ---------------------------------------------------------------- Phase 1
  {
    id: 'hdx.cod-ab-tha',
    organization: 'กรมแผนที่ทหาร ผ่าน UN OCHA (HDX)',
    organizationEn: 'Royal Thai Survey Department via UN OCHA (HDX)',
    datasetName: 'ขอบเขตการปกครองประเทศไทย ระดับจังหวัด อำเภอ ตำบล (COD-AB)',
    datasetNameEn: 'Thailand – Subnational Administrative Boundaries (COD-AB), ADM1–ADM3',
    kind: 'reference',
    license: 'Creative Commons Attribution for Intergovernmental Organisations (CC BY-IGO) — as stated on HDX',
    attribution: 'เขตการปกครอง: กรมแผนที่ทหาร / OCHA COD-AB (HDX)',
    endpoint: 'https://data.humdata.org/dataset/cod-ab-tha',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand ADM0–ADM3 (RTSD, valid_on 2022-01-22); stored here: Nakhon Si Thammarat (TH80) only',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: false,
    phase: 1,
    verificationNote: 'ตรวจสอบแล้ว: ดาวน์โหลด tha_admin_boundaries.shp.zip (HDX 2026-01-26) นำเข้า TH80 ได้ 1 จังหวัด 23 อำเภอ 170 ตำบล วันที่ข้อมูลจากฟิลด์ valid_on — Verified: imported TH80 = 1 province, 23 districts, 170 subdistricts; data date from valid_on.',
  },
  {
    id: 'dopa.villages',
    organization: 'กรมการปกครอง กระทรวงมหาดไทย',
    organizationEn: 'Department of Provincial Administration (DOPA), Ministry of Interior',
    datasetName: 'ข้อมูลที่ตั้งและสภาพทั่วไปของหมู่บ้าน (จังหวัดนครศรีธรรมราช)',
    datasetNameEn: 'Village locations and general conditions (Nakhon Si Thammarat)',
    kind: 'reference',
    license: 'Open Data Common — as stated on GD Catalog (verify exact terms)',
    attribution: 'ที่ตั้งหมู่บ้าน: กรมการปกครอง (GD Catalog)',
    endpoint: 'https://gdcatalog.go.th/dataset/gdpublish-gis-01',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Village points, one file per province; no หมู่ที่ field in the 2023 release; updated yearly',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: false,
    phase: 1,
    verificationNote: 'ตรวจสอบแล้ว: ไฟล์จริง (เผยแพร่ 5 ก.ย. 2566) ได้รับจากเจ้าของโครงการซึ่งดาวน์โหลดจาก URL ทางการ เพราะโฮสต์ opendata_tst.dopa.go.th เข้าถึงไม่ได้จากระบบ 1,636 ระเบียน นำเข้า 1,588 ปฏิเสธ 48 (พิกัดเป็นเมตร 7 จุด นอกจังหวัด 41 จุด ส่วนใหญ่ใช้พิกัดกรุงเทพฯ เป็นค่าแทน) — Verified with the real file (released 2023-09-05) supplied by the project owner from the official URL: 1,636 records, 1,588 imported, 48 rejected (7 projected coordinates, 41 outside the province, mostly a Bangkok placeholder point).',
  },
  {
    id: 'osm.geofabrik',
    organization: 'ผู้ร่วมพัฒนา OpenStreetMap (ไฟล์จาก Geofabrik)',
    organizationEn: 'OpenStreetMap contributors (extract by Geofabrik)',
    datasetName: 'แม่น้ำ ลำธาร คลอง แหล่งน้ำ ถนน ชายฝั่ง และสถานที่ จาก OpenStreetMap',
    datasetNameEn: 'OpenStreetMap rivers, streams, canals, water bodies, roads, coastline and places',
    kind: 'reference',
    license: 'ODbL 1.0 — https://opendatacommons.org/licenses/odbl/1-0/',
    attribution: '© ผู้ร่วมพัฒนา OpenStreetMap (ODbL)',
    endpoint: 'https://download.geofabrik.de/asia/thailand-latest.osm.pbf',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand extract, clipped to the province + 5 km; small-canal completeness varies by area',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 1,
    verificationNote: 'ยังไม่ได้ตรวจสอบ: download.geofabrik.de ตัดการเชื่อมต่อจากสภาพแวดล้อมพัฒนา (connection reset) — Not verified: Geofabrik resets connections from the build environment.',
  },
  {
    id: 'basemap.openfreemap',
    organization: 'OpenFreeMap',
    organizationEn: 'OpenFreeMap',
    datasetName: 'แผนที่ฐานแบบเวกเตอร์ (สว่าง / มืด)',
    datasetNameEn: 'Vector basemap tiles (Positron / Dark)',
    kind: 'reference',
    license: 'unknown — verify at https://openfreemap.org (map data ODbL © OpenStreetMap contributors)',
    attribution: 'OpenFreeMap © OpenMapTiles · ข้อมูล © ผู้ร่วมพัฒนา OpenStreetMap',
    endpoint: 'https://tiles.openfreemap.org/styles/positron',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Global',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: true,
    phase: 1,
    verificationNote: 'ตรวจสอบแล้ว: โหลด style positron ได้ (ยังต้องยืนยันเงื่อนไขการใช้งาน) — Verified: style JSON loads; usage terms still to confirm.',
  },
  {
    id: 'basemap.eox-s2cloudless',
    organization: 'EOX IT Services GmbH',
    organizationEn: 'EOX IT Services GmbH',
    datasetName: 'ภาพดาวเทียม Sentinel-2 cloudless ฉบับปี 2016 (ภาพผสมไร้เมฆ)',
    datasetNameEn: 'Sentinel-2 cloudless 2016 (cloud-free mosaic)',
    kind: 'satellite_derived',
    license: 'unknown — verify (EOX states CC BY 4.0 for the 2016 edition)',
    attribution: 'Sentinel-2 cloudless – https://s2maps.eu by EOX IT Services GmbH (Contains modified Copernicus Sentinel data 2016 & 2017)',
    endpoint: 'https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless_3857/default/g/{z}/{y}/{x}.jpg',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Global mosaic; imagery acquired 2016–2017, not current',
    verified: false,
    verifiedAt: null,
    optional: true,
    phase: 1,
    verificationNote: UNVERIFIED_NETWORK,
  },
  {
    id: 'basemap.opentopomap',
    organization: 'OpenTopoMap',
    organizationEn: 'OpenTopoMap',
    datasetName: 'แผนที่ภูมิประเทศ',
    datasetNameEn: 'Topographic raster tiles',
    kind: 'reference',
    license: 'unknown — verify (OpenTopoMap states CC-BY-SA)',
    attribution: 'ข้อมูล © ผู้ร่วมพัฒนา OpenStreetMap, SRTM · รูปแบบ © OpenTopoMap (CC-BY-SA)',
    endpoint: 'https://tile.opentopomap.org/{z}/{x}/{y}.png',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Global; fair-use tile policy',
    verified: false,
    verifiedAt: null,
    optional: true,
    phase: 1,
    verificationNote: UNVERIFIED_NETWORK,
  },

  {
    id: 'basemap.terrain-aws',
    organization: 'Mapzen / AWS Open Data (Terrain Tiles)',
    organizationEn: 'Mapzen / AWS Open Data (Terrain Tiles)',
    datasetName: 'ความสูงภูมิประเทศสำหรับมุมมอง 3 มิติ',
    datasetNameEn: 'Elevation for the 3D view',
    kind: 'reference',
    license: 'Open data; attribution per https://github.com/tilezen/joerd/blob/master/docs/attribution.md (includes SRTM, GMTED2010, ETOPO1)',
    attribution: 'ภูมิประเทศ: Mapzen Terrain Tiles (AWS Open Data; SRTM, GMTED2010, ETOPO1)',
    endpoint: 'https://registry.opendata.aws/terrain-tiles/',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Global; ~30 m in Thailand (SRTM)',
    verified: true,
    verifiedAt: '2026-10-01',
    optional: true,
    phase: 1,
    verificationNote: 'ตรวจสอบแล้ว: ดึงไทล์ terrarium ได้ (HTTP 200) ใช้เฉพาะมุมมอง 3 มิติ — Verified: terrarium tiles load; used only in the 3D view.',
  },

  // ---------------------------------------------------------------- Phase 2
  {
    id: 'thaiwater.waterlevel',
    organization: 'สถาบันสารสนเทศทรัพยากรน้ำ (สสน.)',
    organizationEn: 'Hydro-Informatics Institute (HII)',
    datasetName: 'ระดับน้ำ (ThaiWater)',
    datasetNameEn: 'Water level (ThaiWater)',
    kind: 'station_observation',
    license: 'unknown — verify',
    attribution: 'ระดับน้ำ: สถาบันสารสนเทศทรัพยากรน้ำ (สสน.) — ThaiWater',
    endpoint: 'https://api-v3.thaiwater.net/api/v1/thaiwater30/public/waterlevel_load',
    requiresKey: false,
    expectedUpdateMinutes: 60,
    coverage: 'Thailand, ~800 telemetry stations from HII, RID, DDPM and others; 28 within the province + 5 km',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/thaiwater.waterlevel/waterlevel_load.json เวลาในข้อมูลไม่มีเขตเวลา ถือเป็นเวลาไทย (+07:00) จากหลักฐานในข้อมูล (ต้องยืนยันกับ สสน.) — Verified with a real sample; timestamps have no timezone and are read as Thai time (+07:00), inferred from the data (confirm with HII).',
  },
  {
    id: 'thaiwater.rain24h',
    organization: 'สถาบันสารสนเทศทรัพยากรน้ำ (สสน.)',
    organizationEn: 'Hydro-Informatics Institute (HII)',
    datasetName: 'ปริมาณฝนสะสม 24 ชั่วโมง (ThaiWater)',
    datasetNameEn: '24-hour rainfall (ThaiWater)',
    kind: 'station_observation',
    license: 'unknown — verify',
    attribution: 'ฝน 24 ชม.: สถาบันสารสนเทศทรัพยากรน้ำ (สสน.) — ThaiWater',
    endpoint: 'https://api-v3.thaiwater.net/api/v1/thaiwater30/public/rain_24h',
    requiresKey: false,
    expectedUpdateMinutes: 60,
    coverage: 'Thailand, ~4,400 rain stations from DWR, RID, HII, DDPM and others; 163 within the province + 5 km',
    verified: true,
    verifiedAt: '2026-09-30',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/thaiwater.rain24h/rain_24h.json เวลาในข้อมูลไม่มีเขตเวลา ถือเป็นเวลาไทย (+07:00) จากหลักฐานในข้อมูล (ต้องยืนยันกับ สสน.) — Verified with a real sample; timestamps have no timezone and are read as Thai time (+07:00), inferred from the data (confirm with HII).',
  },
  {
    id: 'tmd.weather',
    organization: 'กรมอุตุนิยมวิทยา',
    organizationEn: 'Thai Meteorological Department (TMD)',
    datasetName: 'ผลการตรวจอากาศ',
    datasetNameEn: 'Weather observations',
    kind: 'station_observation',
    license: 'TMD copyright; non-commercial redistribution must credit กรมอุตุนิยมวิทยา each time it is shown — verify terms',
    attribution: 'ข้อมูลอุตุนิยมวิทยา: กรมอุตุนิยมวิทยา',
    endpoint: 'https://data.tmd.go.th/api/',
    requiresKey: true,
    expectedUpdateMinutes: 180,
    coverage: 'Thailand, synoptic stations',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 2,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'tmd.warnings',
    organization: 'กรมอุตุนิยมวิทยา',
    organizationEn: 'Thai Meteorological Department (TMD)',
    datasetName: 'ข่าวเตือนภัยสภาพอากาศ',
    datasetNameEn: 'Weather warnings',
    kind: 'warning',
    license: 'TMD copyright; credit กรมอุตุนิยมวิทยา — verify terms',
    attribution: 'คำเตือน: กรมอุตุนิยมวิทยา',
    endpoint: 'https://data.tmd.go.th/api/',
    requiresKey: true,
    expectedUpdateMinutes: 360,
    coverage: 'Thailand',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 2,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'tmd.earthquake',
    organization: 'กรมอุตุนิยมวิทยา',
    organizationEn: 'Thai Meteorological Department (TMD)',
    datasetName: 'แผ่นดินไหวรายวัน (DailySeismicEvent)',
    datasetNameEn: 'Daily seismic events',
    kind: 'station_observation',
    license: 'TMD copyright; credit กรมอุตุนิยมวิทยา — verify terms',
    attribution: 'แผ่นดินไหว: กรมอุตุนิยมวิทยา',
    endpoint: 'https://data.tmd.go.th/api/',
    requiresKey: true,
    expectedUpdateMinutes: 1440,
    coverage: 'Thailand and region',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 2,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'usgs.earthquakes',
    organization: 'สำนักงานสำรวจธรณีวิทยาสหรัฐฯ (USGS)',
    organizationEn: 'U.S. Geological Survey (USGS)',
    datasetName: 'แผ่นดินไหว M4 ขึ้นไปในรัศมี 2,000 กม. (USGS ComCat)',
    datasetNameEn: 'Earthquakes M4+ within 2,000 km (USGS ComCat)',
    kind: 'station_observation',
    license: 'U.S. public domain (USGS-authored data, per USGS "Copyrights and Credits" policy) — policy page not reachable from the build environment; verify',
    attribution: 'แผ่นดินไหว: USGS (ComCat)',
    endpoint: 'https://earthquake.usgs.gov/fdsnws/event/1/query',
    requiresKey: false,
    expectedUpdateMinutes: 15,
    coverage: 'Global catalog; queried here within 2,000 km of the province centre, M ≥ 4.0, last 30 days. Smaller local events are often not listed (TMD is the source for those)',
    verified: true,
    verifiedAt: '2026-10-01',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: ตัวอย่างจริงใน data/samples/usgs.earthquakes/query.geojson เวลาเป็นมิลลิวินาที UTC ขนาด สถานที่ และสถานะ (automatic / reviewed) เป็นของ USGS ไม่มีการคำนวณเพิ่ม — Verified with a real response; times are epoch ms UTC; magnitude, place and review status are USGS\'s own.',
  },
  {
    id: 'nst.cctv',
    organization: 'เทศบาลนครนครศรีธรรมราช (NST Smart City CCTV)',
    organizationEn: 'Nakhon Si Thammarat City Municipality (NST Smart City CCTV)',
    datasetName: 'กล้องวงจรปิดเมืองนครศรีธรรมราช: ตำแหน่ง สถานะ และภาพสด',
    datasetNameEn: 'Nakhon Si Thammarat city CCTV: locations, status and live view',
    kind: 'station_observation',
    license: 'เผยแพร่สาธารณะบนเว็บไซต์ของเทศบาล ยังไม่พบเงื่อนไขการใช้งานที่ระบุชัด (ควรขออนุญาตเทศบาล) — Published openly by the municipality; no explicit terms of use found (permission from the municipality recommended)',
    attribution: 'กล้อง CCTV: เทศบาลนครนครศรีธรรมราช (nstcctv.nakhoncity.org)',
    endpoint: 'https://nstcctv.nakhoncity.org/',
    requiresKey: false,
    expectedUpdateMinutes: 1,
    coverage: 'Cameras of the city municipality (Mueang district): traffic, school fronts, water level, safety zones. Locations and status from the municipality; video plays in the municipality\'s own player',
    verified: true,
    verifiedAt: '2026-10-02',
    optional: false,
    phase: 2,
    verificationNote: 'ตรวจสอบแล้ว: /api/cameras/public ให้รหัส ชื่อ กลุ่ม และพิกัด 222 กล้อง /api/camera-status ให้สถานะ online/offline ภาพสดเปิดผ่านเครื่องเล่นของเทศบาล (/cam/<id>_sub/) ไม่ผ่านระบบนี้ — Verified: 222 cameras with id, name, group and coordinates; status from /api/camera-status; live video is the municipality\'s own player, not relayed by this app.',
  },
  {
    id: 'community.reports',
    organization: 'ประชาชนผู้ใช้ Nakhonsi360',
    organizationEn: 'Members of the public using Nakhonsi360',
    datasetName: 'รายงานภัยพิบัติจากประชาชน (ยังไม่ยืนยัน)',
    datasetNameEn: 'Hazard reports from the public (unverified)',
    kind: 'community',
    license: 'รายงานที่ผู้ใช้ส่งเข้ามา แสดงเฉพาะส่วนที่ไม่ใช่ข้อมูลติดต่อ — User-submitted; contact details are never published',
    attribution: 'รายงานจากประชาชน (ยังไม่ยืนยัน)',
    endpoint: 'https://github.com/nexzerf/nakhonsi360/blob/main/REPORTS.md',
    requiresKey: false,
    expectedUpdateMinutes: 1,
    coverage: 'Nakhon Si Thammarat + 5 km; reports from the last 72 hours on the map',
    verified: true,
    verifiedAt: '2026-10-01',
    optional: false,
    phase: 2,
    verificationNote: 'ข้อมูลจากผู้ใช้ ไม่ใช่ข้อมูลทางการ ไม่ได้ตรวจสอบจนกว่าผู้ปฏิบัติงานจะอัปเดตสถานะ — Reported by the public, not official; unverified until a responder updates its status.',
  },
  {
    id: 'air4thai.aqi',
    organization: 'กรมควบคุมมลพิษ',
    organizationEn: 'Pollution Control Department (PCD) — Air4Thai',
    datasetName: 'คุณภาพอากาศ PM2.5 / AQI',
    datasetNameEn: 'Air quality PM2.5 / AQI',
    kind: 'station_observation',
    license: 'unknown — verify',
    attribution: 'คุณภาพอากาศ: กรมควบคุมมลพิษ (Air4Thai)',
    endpoint: 'http://air4thai.pcd.go.th/services/getNewAQI_JSON.php',
    requiresKey: false,
    expectedUpdateMinutes: 60,
    coverage: 'Thailand; number of stations inside the province to be confirmed',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 2,
    verificationNote: 'ยังไม่ได้ตรวจสอบ: http://air4thai.pcd.go.th ยังไม่อยู่ใน allowlist ส่วน https ใบรับรองไม่ผ่านการตรวจสอบ — Not verified: the http host is not in the allowlist and the https certificate chain does not verify.',
  },
  {
    id: 'gistda.flood',
    organization: 'สำนักงานพัฒนาเทคโนโลยีอวกาศและภูมิสารสนเทศ (GISTDA)',
    organizationEn: 'Geo-Informatics and Space Technology Development Agency (GISTDA)',
    datasetName: 'พื้นที่น้ำท่วมจากดาวเทียม และพื้นที่น้ำท่วมซ้ำซาก',
    datasetNameEn: 'Satellite flood extent and recurrent flood areas',
    kind: 'satellite_derived',
    license: 'unknown — verify',
    attribution: 'น้ำท่วม: GISTDA',
    endpoint: 'https://api-gateway.gistda.or.th/api/2.0/resources',
    requiresKey: true,
    expectedUpdateMinutes: 1440,
    coverage: 'Thailand, per satellite pass',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 2,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'gistda.hotspots',
    organization: 'สำนักงานพัฒนาเทคโนโลยีอวกาศและภูมิสารสนเทศ (GISTDA)',
    organizationEn: 'GISTDA',
    datasetName: 'จุดความร้อนรายวัน',
    datasetNameEn: 'Daily fire hotspots',
    kind: 'satellite_derived',
    license: 'unknown — verify',
    attribution: 'จุดความร้อน: GISTDA',
    endpoint: 'https://fire.gistda.or.th',
    requiresKey: false,
    expectedUpdateMinutes: 1440,
    coverage: 'Thailand',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 2,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'firms.hotspots',
    organization: 'NASA FIRMS',
    organizationEn: 'NASA Fire Information for Resource Management System',
    datasetName: 'จุดความร้อน VIIRS / MODIS (สำรอง)',
    datasetNameEn: 'VIIRS / MODIS active fire (backup)',
    kind: 'satellite_derived',
    license: 'unknown — verify',
    attribution: 'จุดความร้อน: NASA FIRMS',
    endpoint: 'https://firms.modaps.eosdis.nasa.gov/api/area/',
    requiresKey: true,
    expectedUpdateMinutes: 180,
    coverage: 'Global',
    verified: false,
    verifiedAt: null,
    optional: true,
    phase: 2,
    verificationNote: NOT_STARTED,
  },

  // ---------------------------------------------------------------- Phase 3
  {
    id: 'gistda.soilmoisture',
    organization: 'GISTDA',
    organizationEn: 'GISTDA',
    datasetName: 'ข้อมูลความชื้นในดินของประเทศไทย',
    datasetNameEn: 'Soil moisture of Thailand (weekly)',
    kind: 'satellite_derived',
    license: 'unknown — verify',
    attribution: 'ความชื้นในดิน: GISTDA',
    endpoint: 'https://api-gateway.gistda.or.th/api/2.0/resources',
    requiresKey: true,
    expectedUpdateMinutes: 10080,
    coverage: 'Thailand',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 3,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'dmr.landslide',
    organization: 'กรมทรัพยากรธรณี',
    organizationEn: 'Department of Mineral Resources (DMR)',
    datasetName: 'พื้นที่เสี่ยงภัยดินถล่มระดับชุมชน และจุดปลอดภัย',
    datasetNameEn: 'Community landslide risk areas and safe places',
    kind: 'survey',
    license: 'unknown — verify',
    attribution: 'ดินถล่ม: กรมทรัพยากรธรณี',
    endpoint: 'https://gis.dmr.go.th/arcgis/rest/services/DMR_Hazard/WebService_DataCatalog_GeoHazard/MapServer',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 3,
    verificationNote: UNVERIFIED_NETWORK,
  },
  {
    id: 'dmr.shoreline',
    organization: 'กรมทรัพยากรธรณี',
    organizationEn: 'Department of Mineral Resources (DMR)',
    datasetName: 'การเปลี่ยนแปลงแนวชายฝั่ง',
    datasetNameEn: 'Shoreline change study',
    kind: 'survey',
    license: 'unknown — verify',
    attribution: 'แนวชายฝั่ง: กรมทรัพยากรธรณี',
    endpoint: 'https://data.dmr.go.th',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Includes Nakhon Si Thammarat',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 3,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'dmcr.coast',
    organization: 'กรมทรัพยากรทางทะเลและชายฝั่ง',
    organizationEn: 'Department of Marine and Coastal Resources (DMCR)',
    datasetName: 'การกัดเซาะชายฝั่ง ป่าชายเลน สถานภาพชายฝั่ง',
    datasetNameEn: 'Coastal erosion, mangroves, shoreline status',
    kind: 'survey',
    license: 'unknown — verify',
    attribution: 'ชายฝั่ง: กรมทรัพยากรทางทะเลและชายฝั่ง',
    endpoint: 'https://marinegiscenter.dmcr.go.th',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thai coasts',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 3,
    verificationNote: 'ไม่พบ API สาธารณะ ต้องติดต่อหน่วยงาน — No public API found; contact DMCR.',
  },
  {
    id: 'ldd.landuse',
    organization: 'กรมพัฒนาที่ดิน',
    organizationEn: 'Land Development Department (LDD)',
    datasetName: 'การใช้ที่ดิน และกลุ่มชุดดิน',
    datasetNameEn: 'Land use and soil groups',
    kind: 'survey',
    license: 'unknown — verify',
    attribution: 'การใช้ที่ดิน: กรมพัฒนาที่ดิน',
    endpoint: 'https://eis.ldd.go.th',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 3,
    verificationNote: NOT_STARTED,
  },
  {
    id: 'dwr.wetlands',
    organization: 'กรมทรัพยากรน้ำ',
    organizationEn: 'Department of Water Resources (DWR)',
    datasetName: 'พื้นที่ชุ่มน้ำ และชั้นคุณภาพลุ่มน้ำ',
    datasetNameEn: 'Wetlands and watershed classes',
    kind: 'survey',
    license: 'unknown — verify',
    attribution: 'พื้นที่ชุ่มน้ำ: กรมทรัพยากรน้ำ',
    endpoint: 'https://webgis.dwr.go.th/downloads',
    requiresKey: false,
    expectedUpdateMinutes: null,
    coverage: 'Thailand',
    verified: false,
    verifiedAt: null,
    optional: false,
    phase: 3,
    verificationNote: NOT_STARTED,
  },

  // ---------------------------------------------------------------- Phase 4
  {
    id: 'copernicus.sentinel2',
    organization: 'Copernicus Data Space Ecosystem (ESA / EU)',
    organizationEn: 'Copernicus Data Space Ecosystem (ESA / EU)',
    datasetName: 'ภาพดาวเทียม Sentinel-2 และดัชนีพืชพรรณ (NDVI)',
    datasetNameEn: 'Sentinel-2 imagery and NDVI',
    kind: 'satellite_derived',
    license: 'unknown — verify (Copernicus data terms)',
    attribution: 'Contains modified Copernicus Sentinel data',
    endpoint: 'https://dataspace.copernicus.eu',
    requiresKey: true,
    expectedUpdateMinutes: null,
    coverage: 'Global, revisit ~5 days',
    verified: false,
    verifiedAt: null,
    optional: true,
    phase: 4,
    verificationNote: NOT_STARTED,
  },
];

const byId = new Map(SOURCES.map((s) => [s.id, s]));

export function getSource(id: string): DataSource {
  const s = byId.get(id);
  if (!s) throw new Error(`Unknown data source: ${id}`);
  return s;
}

export function findSource(id: string): DataSource | undefined {
  return byId.get(id);
}

/** Static sources loaded into Postgres by the import scripts. */
export const IMPORTED_SOURCE_IDS = ['hdx.cod-ab-tha', 'dopa.villages', 'osm.geofabrik'] as const;
export type ImportedSourceId = (typeof IMPORTED_SOURCE_IDS)[number];
